# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6692204c3aecc0b1acb7c5b7b07dc07e277b118c28601f6fb9f4524adf5703ba228e092976aa5f9ab9fcbb5c832a9ab6d444042185d4fc659a2b2bb30559da03

test:
  secret_key_base: 5f5d4be98b9afb495684d3b599c04f42c49c164dee5b034e30587b4a200f571012234385c822e9297e753932d1df1d3d666ae6a84ddb6b9bde96593ded146f58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
